import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import {
  CheckCircleIcon,
  CircleAlertIcon,
  TriangleAlertIcon,
  XIcon,
} from "lucide-react";
import type { Metadata } from "next";
import { JetBrains_Mono, Outfit } from "next/font/google";
import { Toaster } from "sonner";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(outfit.variable, jetBrainsMono.variable, "antialiased")}
      >
        {children}
        <Toaster
          closeButton
          position="top-center"
          icons={{
            success: <CheckCircleIcon className="!size-4 !text-green-700" />,
            warning: <TriangleAlertIcon className="!text-warning !size-4" />,
            error: <CircleAlertIcon className="!text-destructive !size-4" />,
            close: <XIcon className="size-4" />,
          }}
          toastOptions={{
            unstyled: false,
            classNames: {
              closeButton:
                "!self-baseline !shrink-0 !text-foreground !relative !order-[99] !border-none ![&>svg]:h-4 ![&>svg]:w-4 !h-6 !w-4 !transform-none !pr-0 !bg-transparent",
              icon: "!shrink-0 !h-full !w-4 !m-0 !mt-1 !self-start !items-start",
              toast:
                "!rounded-sm !bg-background border border-border text-foreground !font-sans",
              default:
                "!gap-x-2 !flex !items-center !justify-center !py-3 !px-4 !rounded-md !w-full",
              success: "!bg-green-100 !text-success !border-green-700",
              error: "!bg-red-100 !text-destructive !border-destructive",
              warning: "!bg-yellow-100 !text-amber-600 !border-amber-600",
              loader: "!pb-1",
              content: "!shrink-1 !gap-y-1 !w-full",
              description: "!text-foreground",
            },
          }}
        />
      </body>
    </html>
  );
}
